#01:
SELECT
  TABLE_NAME, COLUMN_NAME, DATA_TYPE, COLUMN_KEY
FROM
  INFORMATION_SCHEMA.COLUMNS
WHERE
  TABLE_SCHEMA IN ('ARTMUSEUM');

#02
SELECT * FROM ART_OBJECT
WHERE ID_NUM ='P_00007';

#03
SELECT * 
FROM ARTIST
ORDER BY NAME ASC;

#04
SELECT *
FROM ART_OBJECT
WHERE ID_NUM IN (
	SELECT ID_NUM
	FROM BORROWED) ;

#05
SELECT ID_NUM, TITLE, ARTIST
FROM (( ARTIST JOIN ART_OBJECT ON NAME = ARTIST) );

#06
UPDATE ARTIST
SET MAIN_STYLE="Abstract"
WHERE NAME='Robert Pruitt';

#07 - here the referential trigger from the foreign key gets rid of object in all other tables
DELETE FROM PAINTING
WHERE ID_NUM = 'P_00002';